Serial.println();
Serial.print("Ligado: ");
Serial.println(ligado);
Serial.print("Frio: ");
Serial.println(frio);
Serial.print("Quente: ");
Serial.println(quente);
Serial.print("Espera do inicio: ");
Serial.println(esperaInicio);
  Serial.println();
  Serial.println("************************");
  Serial.println();
Serial.print("Relé Estado Quente: ");
Serial.println(estadoRele1);
Serial.print("Relé Estado Frio: ");
Serial.println(estadoRele2);
Serial.print("Relé Velocidade 1: ");
Serial.println(estadoRele3);
Serial.print("Relé Velocidade 2: ");
Serial.println(estadoRele4);
Serial.print("Relé Velocidade 3: ");
Serial.println(estadoRele5);
  Serial.println();
  Serial.println("************************");
  Serial.println();
Serial.print("Temperatura Desejada Estado frio: ");
Serial.println(temperaturaDesejadaFrio);
Serial.print("Temperatura Desejada Estado quente: ");
Serial.println(temperaturaDesejadaQuente);
Serial.print("Evaporador no limite: ");
Serial.println(limiteEvaporador);
Serial.print("Soma da Diferenca Ambiente no estado Frio: ");
Serial.println(somaDiferencaAmbienteFrio);
Serial.print("Soma da Diferenca limite do evaporador: ");
Serial.println(somaDiferencaLimite);
Serial.print("Inversão de estado: ");
Serial.println(inversaoDeEstado);
Serial.print("Auxiliar de Inversão: ");
Serial.println(auxiliarDeInversao);
Serial.print("Ultimo botão apertado: ");
Serial.println(guardaBotaoApertado);
Serial.println();
Serial.println();